const MPI05 = Math.PI * 0.5;

/** Initial values for 3d sliders */
export const slider3dInitVal = {
    ct: {
      thresholdIsosurf: 0.43,
      thresholdTissue1: 0.1,
      thresholdTissue2: 0.35,
      opacityTissue: 0.15,
      startRotX: 0.0,
      startRotY: 0.0,
      lightDirComp: 0.5773,
      brightness: 0.69,
    },
    lungs: {
      thresholdIsosurf: 0.6,
      thresholdTissue1: 0.02,
      thresholdTissue2: 0.09,
      opacityTissue: 0.17,
      startRotX: -MPI05,
      startRotY: Math.PI,
      lightDirComp: -0.5773,
      brightness: 0.82,
    },
    pelvis: {
      thresholdIsosurf: 0.64,
      thresholdTissue1: 0.13,
      thresholdTissue2: 0.45,
      opacityTissue: 0.3,
      startRotX: -MPI05,
      startRotY: Math.PI,
      lightDirComp: -0.5773,
      brightness: 0.5,
    },
    nifti: {
      thresholdIsosurf: 0.5,
      thresholdTissue1: 0.12,
      thresholdTissue2: 0.35,
      opacityTissue: 0.3,
      startRotX: -MPI05,
      startRotY: 0.0,
      lightDirComp: -0.5773,
      brightness: 0.5,
    },
    hdr: {
      thresholdIsosurf: 0.95,
      thresholdTissue1: 0.12,
      thresholdTissue2: 0.25,
      opacityTissue: 0.32,
      startRotX: 0.0,
      startRotY: 0.0,
      lightDirComp: -0.5773,
      brightness: 0.5,
    },
    undefined: {
      thresholdIsosurf: 0.46,
      thresholdTissue1: 0.09,
      thresholdTissue2: 0.30,
      opacityTissue: 0.23,
      startRotX: -MPI05,
      startRotY: Math.PI,
      lightDirComp: -0.5773,
      brightness: 0.56,
    },
  };